"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),test=require("node:test");
const root=path.resolve(__dirname,".."),html=fs.readFileSync(path.join(root,"renderer/out/index.html"),"utf8"),css=fs.readFileSync(path.join(root,"renderer/out/assets/app.css"),"utf8"),renderer=fs.readFileSync(path.join(root,"renderer/out/assets/app.js"),"utf8");
test("workflow keeps four clear sections without decorative header steps",()=>{assert.equal((html.match(/class="workflow-index"/g)||[]).length,4);assert.match(html,/Выбрать изображение/);assert.match(html,/Профиль обработки/);assert.match(html,/Сохранение/);assert.match(html,/Запуск обработки/);assert.doesNotMatch(html,/workflow-completion/);});
test("sidebar source status follows selection and clear actions",()=>{assert.match(html,/id="sidebar-source-label"/);assert.match(renderer,/sidebarSourceLabel\.textContent = basename\(path\)/);assert.match(renderer,/sidebarSourceLabel\.textContent = "Файл ещё не выбран"/);assert.match(renderer,/sidebar-select-file-button/);});
test("primary typography stays readable",()=>{assert.match(css,/--rail-width: 68px/);assert.match(css,/--controls-width: 312px/);assert.match(css,/font-family: "Segoe UI Variable"/);assert.match(css,/\.drop-empty h3 \{[^}]*font-size: 21px/);assert.doesNotMatch(css,/font-size:\s*[0-8](?:\.\d+)?px/);});

test("enhance header keeps only the reset action",()=>{assert.doesNotMatch(html,/AI IMAGE STUDIO|Новое улучшение|Четыре шага до готового результата|workflow-completion/);assert.match(html,/<div class="panel-heading controls-heading"><button[^>]*id="reset-controls"/);assert.match(css,/body\[data-ui-revision="studio-rc6"\] \.panel-heading\.controls-heading \{[^}]*justify-content: flex-end/s);});
test("navigation rail remains usable when controls are collapsed",()=>{assert.match(css,/body\.sidebar-compact \{ --sidebar-width: 74px/);assert.match(css,/body\.sidebar-compact \.primary-nav \{[^}]*grid-template-columns: 1fr/);assert.match(css,/body\.sidebar-compact \.enhance-workflow/);});
