"use strict";
const fs=require("fs"), fsp=require("fs/promises"), path=require("path");
const {spawn}=require("child_process");
function packRoot(app,tier="pro"){return path.join(app.getPath("userData"),"local-ai",tier==="ultra"?"photo-restore-ultra":"photo-restore-pro");}
function resourceRoot(app,isPackaged){return isPackaged?path.join(process.resourcesPath,"local-ai"):path.join(app.getAppPath(),"resources","local-ai");}
function files(app,tier="pro"){const root=packRoot(app,tier);return{root,manifest:path.join(root,"installed.json"),python:path.join(root,"python","python.exe"),runner:path.join(root,"runtime",tier==="ultra"?"ultra_restore_runner.py":"local_restore_runner.py"),models:path.join(root,"models"),repo:path.join(root,"DiffBIR")};}
function folderBytes(root){let bytes=0;if(fs.existsSync(root)){const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);e.isDirectory()?walk(p):bytes+=fs.statSync(p).size;}};walk(root);}return bytes;}
function tierStatus(app,tier){const f=files(app,tier);let m=null;try{m=JSON.parse(fs.readFileSync(f.manifest,"utf8").replace(/^\uFEFF/,""));}catch{}
 const faceWeights=[path.join(f.models,"gfpgan","weights","detection_Resnet50_Final.pth"),path.join(f.models,"gfpgan","weights","parsing_parsenet.pth")];
 const required=tier==="ultra"?[f.python,f.runner,path.join(f.models,"DiffBIR_v2.1.pt"),path.join(f.models,"GFPGANv1.4.pth"),path.join(f.models,"RealESRGAN_x4plus.pth"),...faceWeights,path.join(f.repo,"weights","sd2.1-base-zsnr-laionaes5.ckpt"),path.join(f.repo,"weights","realesrgan_s4_swinir_100k.pth"),path.join(f.repo,"weights","DiffBIR_v2.1.pt"),path.join(f.repo,"inference.py")]:[f.python,f.runner,path.join(f.models,"GFPGANv1.4.pth"),path.join(f.models,"RealESRGAN_x4plus.pth"),...faceWeights];
 const manifestOk=Number(m?.runtimePatch||0)>=3;
 return{installed:Boolean(m&&manifestOk&&required.every(fs.existsSync)),backend:m?.backend||null,installedAt:m?.installedAt||null,bytes:folderBytes(f.root),root:f.root,version:m?.version||null};}
function getStatus(app){return{...tierStatus(app,"pro"),pro:tierStatus(app,"pro"),ultra:tierStatus(app,"ultra")};}
function normalizePercent(value){if(value==null)return 0;const m=String(value).match(/-?\d+(?:[\.,]\d+)?/);if(!m)return 0;const n=Number(m[0].replace(",","."));return Number.isFinite(n)?Math.max(0,Math.min(100,Math.round(n))):0;}
function runProcess(command,args,{signal,onLine,cwd}={}){return new Promise((resolve,reject)=>{const child=spawn(command,args,{windowsHide:true,cwd});let stderr="";const h=d=>String(d).split(/\r?\n/).filter(Boolean).forEach(l=>onLine?.(l));child.stdout.on("data",h);child.stderr.on("data",d=>{stderr+=String(d);h(d)});const abort=()=>{try{child.kill()}catch{}};signal?.addEventListener("abort",abort,{once:true});child.on("error",reject);child.on("exit",c=>{signal?.removeEventListener("abort",abort);c===0?resolve():reject(new Error(stderr.trim()||`Процесс завершился с кодом ${c}`));});});}
async function installPack({app,isPackaged,backend="auto",tier="pro",signal,onProgress}){tier=tier==="ultra"?"ultra":"pro";const root=packRoot(app,tier);await fsp.mkdir(root,{recursive:true});const script=path.join(resourceRoot(app,isPackaged),tier==="ultra"?"install-ultra-restore.ps1":"install-local-restore.ps1");if(!fs.existsSync(script))throw new Error("Установщик AI-пакета отсутствует.");await runProcess("powershell.exe",["-NoProfile","-ExecutionPolicy","Bypass","-File",script,"-InstallRoot",root,"-Backend",backend],{signal,onLine(line){const m=line.match(/^AVELUNE_STAGE:([^:]*):(.*)$/);if(m)onProgress?.({tier,percent:normalizePercent(m[1]),message:m[2]});}});return getStatus(app);}
async function removePack(app,tier="pro"){await fsp.rm(packRoot(app,tier),{recursive:true,force:true});return getStatus(app);}
async function restoreLocal({app,inputPath,outputPath,strength=75,scale=2,tile=0,quality="balanced",tier="pro",signal,onProgress}){tier=tier==="ultra"?"ultra":"pro";const f=files(app,tier),status=tierStatus(app,tier);if(!status.installed)throw new Error(tier==="ultra"?"Сначала установите пакет Photo Restore Ultra в настройках.":"Сначала установите пакет Photo Restore Pro в настройках.");const args=[f.runner,"--input",inputPath,"--output",outputPath,"--models",f.models,"--strength",String(Math.max(0,Math.min(1,Number(strength)/100))),"--scale",String(scale),"--tile",String(tile||0),"--quality",quality];if(tier==="ultra")args.push("--repo",f.repo);await runProcess(f.python,args,{signal,onLine(line){const m=line.match(/^AVELUNE_PROGRESS:(\d+):(.*)$/);if(m)onProgress?.(`${m[1]}%\n${m[2]}\n`);}});return outputPath;}
module.exports={getStatus,installPack,removePack,restoreLocal};
